### PR TITLE
feat: Sync awareness status

### PR DESCRIPTION
**Pull request by martolini**
First pass a syncing awareness status.

It's unclear to me if this also adds the subscriber as an entity in the awareness state, need to write some tests to understand how it works.

My prettier config also added some flair to the codebase, sorry about that.

[An attempt to solving #3]

### CODE REVIEW

**Comment by kapv89** [comment]
Hi @martolini, this PR broadcasts awareness updates to all the websocket servers connected to the doc's room, but it doesn't do anything to initialize the awareness state of a WSSharedDoc. Also, simply copying awareness state from one server instance to another seems a bit incorrect too. Let me go to the forums and see if someone can help with a proper solution. I'll keep you updated

**Comment by martolini** [comment]
Thanks for the feedback!

It does -- you're absolutely right. I scanned the forums quickly last night before throwing together this (which I saw over at https://github.com/yjs/y-redis/issues/8)!

The initialization part is a very good point, it's unclear to me how important it is (I'd expect it to update quite frequently in most use cases). Let me know if I can help (I'm also on the yjs discord with the same name) 🤓

**Comment by kapv89** [comment]
Hi @martolini ... thanks for that link to the issue on y-redis. I also got a reply on the forums https://discuss.yjs.dev/t/scalability-of-y-websocket-server/274/13?u=kapv89 ... seems like what you are trying to do works.

However, the way it's done right now will cause an infinite loop ... awareness-change would come in from the websocket, will be published to redis, which again cause the awarenessChangeHandler to run and causes another publish to redis and so on.

I think what is needed is to change the type of variable for origin in awarenessChangeHandler, where it could be a websocket or redis connection, and to only publish the awareness update to redis when the origin is of type websocket. Please make this change and I'll merge the PR.

**Comment by kapv89** [comment]
Hi @martolini ... thanks for the PR. With it's help, I have been able to make the changes needed to scale awareness across a websocket-server-cluster and perform some basic tests. You can view the updated code in the repo and you can use this repo to perform further tests - https://github.com/kapv89/yjs-scalable-ws-backend-test

**Pull request closed without merging**
